title: Ouïedire
default_lang: fr
taxonomies:
  - artist
  - dj
metadata:
  description: 'J''en ai déjà entendu parler quelque part'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
